import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from matplotlib.ticker import LogFormatterExponent
from sympy import symbols, expand, sympify, Poly, collect, simplify
from scipy.linalg import lstsq
import sympy as sp

from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication_application

from dae_finder import sequentialThLin
from Comparison import standardize_columns, TimeSeriesDerivative
from Basis import OrthogonalLibrary, Monomials, normalization
from PolyConvert import OrthogonalToPolynomialConverter, EquationDenormalizer, MatrixEquationDenormalizer
import pysindy as ps

import re


class Recover_Model_dae:
    def __init__(self,candidate_lib_full:pd.DataFrame,data_derivatives:pd.DataFrame,coef_threshold,threshold_scan):
        # data_derivatives: dataframe generated by Comparison.compute_time_derivatives
        # threshold: coefficient threshold, depends on parameter values
        self.candidate_lib_full = candidate_lib_full
        self.data_derivatives = data_derivatives
        self.coef_threshold = coef_threshold
        self.threshold_scan = threshold_scan

        self.mapping, self.model_expression = self._recovered_model()
        self.model = self._model_to_dataframe()
    
    def _recovered_equation(self,target_column):
        seq_th_model = sequentialThLin(
            model_id = "RR",
            coef_threshold = self.coef_threshold,
            fit_intercept = False
        )
        #print("DEBUG – created STLSQ with coef_threshold =", seq_th_model.coef_threshold)
        seq_th_model.fit(self.candidate_lib_full,self.data_derivatives[target_column])

        final_coef = seq_th_model.coef_history_df.iloc[-1].fillna(0.0)
        discovered_terms = final_coef[final_coef != 0]
        # Build RHS string with correct ± signs
        rhs_terms = []
        for name, coef in discovered_terms.items():
            sign = "+" if coef >= 0 else "-"
            rhs_terms.append(f"{sign} {abs(coef):.4g}*{name}")
        rhs = " ".join(rhs_terms).lstrip("+ ").replace("+ -", "- ")

        equation = f"{target_column} = {rhs}"
        return discovered_terms,equation
    
    def _recovered_model(self):
        col_feature = [col for col in self.data_derivatives.columns if col not in ['t_Exp','t_Sim']]
        self.features = col_feature
        mapping = {}
        for feature in col_feature:
            discovered_terms,equation = self._recovered_equation(target_column=feature)
            mapping[feature] = {
                'discovered_terms': discovered_terms,
                'equation': equation
            }
        model_expression = "\n".join(
            mapping[feature]['equation'] for feature in col_feature
        )
        return mapping, model_expression
    
    def _model_to_dataframe(self):
        rows = []
        for feature in self.features:
            equation = self.mapping[feature]['equation']
            lhs,rhs = equation.split('=',1)
            rows.append({'Variable':lhs.strip(),
                        'Equation':rhs.strip()})
        return pd.DataFrame(rows)

class WhitenedOptimizer:
    """
    A thin wrapper for performing “empirical whitening” on incoming PySINDy optimizers:
      1) Scale only (no centering): s_j = sqrt(mean(Theta[:,j]^2))   # RMS per column
      2) G = (Theta_s^T Theta_s) / n,  W = G^{-1/2} (eigh)
      3) Theta_ortho = Theta_s @ W
      4) Call the underlying optimizer on Theta_ortho to obtain a_hat.
      5) Projection back to the original space: c = (W @ a_hat) / s
    """
    def __init__(self, base_optimizer, eps: float = 1e-12):
        self.base = base_optimizer
        self.eps = eps
        self.coef_ = None  # Post-return assignment

    def _compute_whitener(self, Theta):
        n, p = Theta.shape
        # Scaling only (RMS), without mean subtraction, to avoid affecting the constant column.
        s = np.sqrt(np.mean(Theta ** 2, axis=0))
        s[s < self.eps] = 1.0
        Theta_s = Theta / s
        # Experience Gram
        G = (Theta_s.T @ Theta_s) / max(n, 1)
        G = G + self.eps * np.eye(p)
        w, V = np.linalg.eigh(G)
        w[w < self.eps] = self.eps
        W = V @ np.diag(1.0 / np.sqrt(w)) @ V.T
        return Theta_s, s, W

    def fit(self, Theta, y):
        Theta_s, s, W = self._compute_whitener(Theta)
        Theta_ortho = Theta_s @ W
        fitted = self.base.fit(Theta_ortho, y)

        # Pull coefficients from the wrapped optimizer (before mapping back)
        coef_hat = getattr(self.base, "coef_", None)
        if coef_hat is None:
            coef_hat = getattr(fitted, "coef_", None)
        if coef_hat is None:
            raise RuntimeError("Wrapped optimizer did not expose 'coef_' after fit().")

        coef_hat = np.asarray(coef_hat)
        p = Theta.shape[1]

        # Record the original layout to restore afterwards
        orig_ndim = coef_hat.ndim
        orig_shape = coef_hat.shape
        # Determine (p, m) canonical form
        if orig_ndim == 1:
            # Expect (p,)
            if coef_hat.shape[0] != p:
                raise ValueError(
                    f"coef_ length {coef_hat.shape[0]} does not match n_features {p}."
                )
            C0 = coef_hat.reshape(p, 1)
            restore = ("vector", None)  # restore as 1D
        elif orig_ndim == 2:
            if coef_hat.shape[0] == p:
                # (p, m)
                C0 = coef_hat
                restore = ("pm", orig_shape)
            elif coef_hat.shape[1] == p:
                # (m, p) -> transpose to (p, m)
                C0 = coef_hat.T
                restore = ("mp", orig_shape)
            else:
                raise ValueError(
                    f"coef_ has incompatible shape {orig_shape}; expected one dimension equal to p={p}."
                )
        else:
            raise ValueError(f"coef_ has unsupported ndim={orig_ndim}.")

        # Map back to original feature space in canonical (p, m)
        C_s = W @ C0              # (p, p) @ (p, m) -> (p, m)
        C = C_s / s[:, None]      # row-wise scale back

        # Restore to the original layout expected by the base optimizer / PySINDy
        kind, meta = restore
        if kind == "vector":
            self.coef_ = C[:, 0]                  # (p,)
        elif kind == "pm":
            self.coef_ = C                        # (p, m)
        elif kind == "mp":
            self.coef_ = C.T                      # (m, p)
        else:
            # Fallback: keep canonical (p, m)
            self.coef_ = C

        return self

    # Other properties/methods of the transparent underlying optimizer (such as threshold, max_iter, etc.)
    def __getattr__(self, name):
        if name in ("base", "eps", "coef_"):    
            return super().__getattribute__(name)
        return getattr(self.base, name)
    
class Recover_Model_sindy:
    def __init__(self,data,differential_order,poly_degree,threshold,method,
                 threshold_scan=None,Xdot=None,debug=True,after_threshold=None,
                 L=None, U=None,denormalize=True):
        # data: DataFrame -- contains all columns including states and time
        # for orthogonal basis, the data should have been normalized
        # method: basis library used, the default one is monomial library
        # L,U : lower and upper bound of the original data
        self.data = data
        self.differential_order = differential_order
        self.poly_degree = poly_degree
        self.threshold = threshold
        self.threshold_scan = threshold_scan
        self.Xdot = Xdot
        self.method = method
        self.debug = debug
        # Post-expansion coefficient filter (on final polynomial equations)
        self.after_threshold = after_threshold
        self.denormalize = denormalize # Whether to denormalize, default is True

        self.data_states, self.time = self._preprocess()
        self.features = list(self.data_states.columns)

        self.L, self.U = L.to_dict(), U.to_dict()

        #if self.method == 'Legendre' or 'Chebyshev':
            #self.data_norm = normalization(self.data_states)[0]

        if self.method == 'Monomial':
            self.model_expression = self._recovered_model_monomial()
        else:
            self.model_expression = self._recovered_model_orthogonal()

    def _remap_legendre_linear_names_by_corr(self, eq_list):
        """Return a new eq_list where *single* linear Legendre tags P_1(xi) are renamed
        to the variable whose raw state column correlates the most with that library column.
        Products like 'P_1(xi) P_1(xj)' are left untouched.
        This is purely data-driven and does not inject model priors.
        """
        if self.method != 'Chebyshev':
            return eq_list
        mdl = getattr(self, 'model', None)
        if mdl is None:
            return eq_list
        lib = mdl.feature_library
        X = np.asarray(self.data_states, dtype=float)
        try:
            Theta = lib.transform(X)
        except Exception:
            Theta = lib.transform([X])[0]
        try:
            names = lib.get_feature_names(input_features=self.features)
        except Exception:
            names = lib.get_feature_names()

        # Identify linear Legendre columns by name pattern
        lin_idx = []
        lin_name = []
        for j, nm in enumerate(names):
            if re.fullmatch(r"P_1\(x\w+\)", nm) or re.fullmatch(r"P1\(x\w+\)", nm):
                lin_idx.append(j)
                lin_name.append(nm)
        if not lin_idx:
            return eq_list

        # Build name -> canonical tag mapping by max |corr| with raw state columns
        Xarr = np.asarray(X, float)
        mapping = {}
        for j, nm in zip(lin_idx, lin_name):
            corrs = [abs(np.corrcoef(Theta[:, j], Xarr[:, k])[0, 1]) for k in range(Xarr.shape[1])]
            k_best = int(np.argmax(corrs))
            mapping[nm] = f"P_1({self.features[k_best]})"
        if self.debug:
            print("[REMAP] linear Legendre tags:")
            for k in mapping:
                print(f"  {k} -> {mapping[k]}")

        # Replace only tokens that contain exactly one P_1(...) tag (singletons),
        # leaving product terms intact
        def remap_rhs(rhs: str) -> str:
            # split into signed terms while preserving signs
            parts = re.findall(r"[+-]?\s*[^+-]+", rhs)
            new_parts = []
            for term in parts:
                tags = re.findall(r"P_1\(x\w+\)|P1\(x\w+\)", term)
                if len(tags) == 1:
                    t_old = tags[0]
                    t_new = mapping.get(t_old, t_old)
                    new_parts.append(term.replace(t_old, t_new))
                else:
                    new_parts.append(term)
            # rejoin and normalize spaces/signs
            out = " ".join(p.strip() for p in new_parts).strip()
            out = re.sub(r"\+\s+-", "- ", out)
            out = re.sub(r"\s+", " ", out)
            return out

        return [remap_rhs(rhs) for rhs in eq_list]

    def _diagnose_linear_alignment(self):
        """Call immediately after fitting is complete:
        - Verify that the order of self.features matches that of self.model.feature_names_.
        - Construct the library matrix Theta with feature names;
        - For each state equation, print the projection <phi_j, y> 
            of that state onto all “linear bases” (xj or P1(xj)).
          And the values of the final coefficient matrix Xi on these columns, 
          facilitating the identification of whether x2/x3 is misplaced.
        """
        try:
            mdl = self.model
        except Exception:
            print("[DIAG] model not set; skip.")
            return

        # 1) Name and Sequence Alignment Check
        model_names = list(getattr(mdl, 'feature_names_', self.features))
        if model_names != self.features:
            print("[DIAG][WARN] self.features and model.feature_names_ Sequence inconsistency:\n\tself.features=", self.features, "\n\tmodel.feature_names_=", model_names)
        else:
            print("[DIAG] feature name order OK ✓")

        # 2) Constructing the library matrix and feature names 
        # (compatible with OrthogonalLibrary's list-of-trajectories API)
        lib = mdl.feature_library
        X = np.asarray(self.data_states, dtype=float)
        try:
            Theta = lib.transform(X)
        except Exception:
            Theta = lib.transform([X])[0]
        try:
            lib_names = lib.get_feature_names(input_features=self.features)
        except Exception:
            lib_names = lib.get_feature_names()
        Xi = np.asarray(mdl.coefficients())  # shape (n_features, n_states)

        # 3) Identify the column index for the “linear term”（monomial: xj; Legendre: P1(xj)/P_1(xj)）
        def linear_idx_for(var):
            # Exact match for monomial name
            if var in lib_names:
                return lib_names.index(var)
            # First-order basis matching Legendre
            patts = [rf"P1\({re.escape(var)}\)", rf"P_1\({re.escape(var)}\)"]
            for p in patts:
                for k, nm in enumerate(lib_names):
                    if re.fullmatch(p, nm):
                        return k
            return None

        idx_linear = {v: linear_idx_for(v) for v in self.features}
        print("[DIAG] linear feature indices:", idx_linear)

        # 4) For each equation, print: <phi_lin, y> and Xi[lin, j]
        if self.Xdot is None:
            t = np.asarray(self.time, dtype=float).reshape(-1)
            Ydot = np.gradient(np.asarray(self.data_states, dtype=float), t, axis=0, edge_order=self.differential_order)
        else:
            Ydot = np.asarray(self.Xdot, dtype=float)

        for j, var in enumerate(self.features):
            y = Ydot[:, j]
            print(f"\n[DIAG] Equation for d{var}/dt")
            # List the projections and coefficients of linear terms in variable order.
            rows = []
            for v in self.features:
                idx = idx_linear.get(v)
                if idx is None:
                    rows.append((v, None, None))
                    continue
                proj = float(Theta[:, idx].T @ y)
                coef = float(Xi[idx, j]) if idx < Xi.shape[0] else np.nan
                rows.append((v, proj, coef))
            # Print
            print("      var       <phi, y>         coef")
            for v, pr, cf in rows:
                pr_s = f"{pr: .6e}" if pr is not None else "   (NA)   "
                cf_s = f"{cf: .6e}" if cf is not None else "   (NA)   "
                print(f"    {v:>6s}   {pr_s:>14s}   {cf_s:>14s}")

    def _preprocess(self):
        data, time_col = standardize_columns(self.data)
        if isinstance(time_col, list):
            time_col_name = time_col[0]
        else:
            time_col_name = time_col
        self.time_col_name = time_col_name
        time = data[self.time_col_name].to_numpy()
        data_states = data.copy().drop(columns={time_col})

        # Preserve the *original* state column order from the user input
        orig_state_cols = [c for c in self.data.columns if c != time_col_name]
        candidate_cols = [c for c in data.columns if c != time_col_name]
        if all(c in candidate_cols for c in orig_state_cols) and len(orig_state_cols) > 0:
            data_states = data.loc[:, orig_state_cols].copy()
        else:
            # Fallback: keep whatever order standardize_columns produced (excluding time)
            data_states = data.loc[:, candidate_cols].copy()

        self.features = list(data_states.columns)
        #if self.method == 'Chebyshev' or self.method == 'Legendre':
            #self.data_norm = normalization(data_states)[0]
        print("features:", self.features, "n_vars=", len(self.features))
        return data_states, time
    
    def _build_equation_list_from_rhs(self, eq_list):
        states, rhs_raw = [], []
        #for var, eq in zip(model.feature_names, eq_list):
        for var, eq in zip(self.features, eq_list):
            states.append(f'd{var}/dt')
            rhs_raw.append(eq.strip())
        def clean(eq: str) -> str:
            eq = re.sub(r'\+\s+-', '- ', eq)
            eq = re.sub(r'\s+', ' ', eq).strip()
            return eq
        rhs = [clean(s) for s in rhs_raw]
        df = pd.DataFrame({
            'Varaiable': states,
            'Equation': rhs
        })
        return df
    
    def _build_equation_list_for_denorm(self, eq_rhs):
        """
        Build ['dxi/dt = <rhs_i>'] for the denormalization pipeline.
        - Ensures empty RHS becomes '0'
        - Normalizes signs/spaces before denormalization (so denorm works on clean strings)
        - Pads to self.features length if needed
        """
        out = []
        n = len(eq_rhs)
        for i, var in enumerate(self.features):
            rhs = (eq_rhs[i] if i < n else "").strip()
            rhs = re.sub(r'\+\s+-', '- ', rhs)
            rhs = re.sub(r'\s+', ' ', rhs).strip()
            if rhs == "":
                rhs = "0"
            out.append(f"d{var}/dt = {rhs}")
        return out

    def _convert_orthogonal_to_polynomial(self, rhs_list):
        """
        Convert SINDy RHS strings from an orthogonal basis to monomial polynomial strings
        WITHOUT denormalization. Returns a list of 'dvar/dt = ...' strings in self.features order.
        """
        converter = OrthogonalToPolynomialConverter(max_degree=self.poly_degree, basis=self.method)
        polynomial_model = converter.convert_sindy_model(rhs_list, self.features)
        equation_list = []
        for var in self.features:
            poly = polynomial_model.get(var)
            if poly is None:
                equation_list.append(f"d{var}/dt = ")
            else:
                equation_list.append(f"d{var}/dt = {poly._to_string()}")
        return equation_list

    def _denormalize_and_format(self, equation_list):
        """
        Apply denormalization (based on self.method, self.L, self.U) and return a tidy DataFrame.
        This method performs only: denormalize -> optional after-threshold -> pretty print.
        It assumes equation_list are full strings like 'dxi/dt = ...' in monomial basis.
        """
        denormalizer = MatrixEquationDenormalizer(self.L, self.U, self.method)

        if self.denormalize is True:
            original_equations = denormalizer.denormalize_equations(equation_list)
        else:
            original_equations = equation_list

        # Parse 'dx/dt = ...' into map
        eq_map = {}
        for eq in original_equations:
            parts = eq.split('=', 1)
            lhs = parts[0].strip()
            rhs = parts[1].strip() if len(parts) > 1 else ''
            m = re.match(r"^d(?P<var>.+)/dt$", lhs)
            if m:
                var_name = m.group('var').strip()
                eq_map[var_name] = rhs

        # Build rows in self.features order
        states, rhs_raw = [], []
        for var in self.features:
            rhs_raw.append(eq_map.get(var, ''))
            states.append(f'd{var}/dt')

        # Clean up
        def clean(eq: str) -> str:
            eq = re.sub(r'\+\s+-', '- ', eq)
            eq = re.sub(r'\s+', ' ', eq).strip()
            return eq
        rhs = [clean(s) for s in rhs_raw]

        # Optional post-expansion hard threshold on final polynomial equations
        if getattr(self, 'after_threshold', None) is not None and float(self.after_threshold) > 0:
            thr = float(self.after_threshold)
            rhs_filtered = []
            for i, eq in enumerate(rhs):
                new_eq, n_removed = self._filter_equation_terms(eq, self.features, thr)
                rhs_filtered.append(new_eq)
                if n_removed > 0:
                    print(f"[AFTER-THRESH] filtered {n_removed} term(s) in d{self.features[i]}/dt with threshold={thr}")
            rhs = rhs_filtered

        rhs = [self._pretty_equation_rhs(s) for s in rhs]
        return pd.DataFrame({'Variable': states, 'Equation': rhs})

    def _recovered_model_monomial(self):
        #differential_method = ps.FiniteDifference(self.differential_order)
        feature_library = ps.PolynomialLibrary(self.poly_degree,include_bias=False)
        optimizer = ps.STLSQ(threshold=self.threshold)
        feature_names = self.features
        
        if self.Xdot is None:
            differential_method = ps.FiniteDifference(self.differential_order)
            #X_dot = np.gradient(X,t,axis=0,edge_order=self.differential_order)
            model = ps.SINDy(
                differentiation_method=differential_method,
                feature_library = feature_library,
                optimizer = optimizer,
                feature_names = feature_names
            )
            self.model = model
            model.fit(self.data_states, t=self.time, x_dot=self.Xdot)
            #model.fit(self.data_states,t = self.time)
            #if getattr(self, 'debug', False):
                #print("\n===== DIAG (monomial) =====")
                #self._diagnose_linear_alignment()
        else:
            model = ps.SINDy(
                feature_library=feature_library,
                optimizer=optimizer,
                feature_names=feature_names
            )
            self.model = model
            model.fit(self.data_states,t=self.time,x_dot=self.Xdot)
        #if getattr(self, 'debug', False):
            #print("\n===== DIAG (monomial) =====")
            #self._diagnose_linear_alignment()
        eq_rhs = model.equations()

        # Setting for denormalized model (Compare with Legendre and Chebyshev)
        #equation_list = self._build_equation_list_for_denorm(eq_rhs)
        #return self._denormalize_and_format(equation_list) 

        # Setting for unnormalized model (Compare with Laguerre)
        equation_list = self._build_equation_list_from_rhs(eq_rhs)

        # --- Optional: filter small coefficients on the final (monomial) equations ---
        if getattr(self, 'after_threshold', None) is not None and float(self.after_threshold) > 0:
            thr = float(self.after_threshold)
            new_rhs = []
            for i, row in equation_list.iterrows():
                rhs_in = str(row['Equation']).strip()
                rhs_out, n_removed = self._filter_equation_terms(rhs_in, self.features, thr)
                if self.debug and n_removed > 0:
                    var_name = str(row['Varaiable']) if 'Varaiable' in row else (str(row['Variable']) if 'Variable' in row else f'd{self.features[i]}/dt')
                    print(f"[AFTER-THRESH][Monomial] filtered {n_removed} term(s) in {var_name} with threshold={thr}")
                new_rhs.append(rhs_out)
            equation_list['Equation'] = new_rhs

        # Pretty-print RHS to 3 decimals and implicit multiplication style
        equation_list['Equation'] = [self._pretty_equation_rhs(s) for s in equation_list['Equation']]

        return equation_list
    
    def _recovered_model_orthogonal(self):
        feature_library = OrthogonalLibrary(degree=self.poly_degree, method=self.method,
                                            include_bias=True)
        optimizer = ps.STLSQ(threshold=self.threshold)
        #optimizer = WhitenedOptimizer(base_optimizer)
        feature_names = self.features

        if self.Xdot is None:
            differential_method = ps.FiniteDifference(self.differential_order)
            model = ps.SINDy(
                differentiation_method=differential_method,
                feature_library=feature_library,
                optimizer=optimizer,
                feature_names=feature_names
            )
            self.model = model
            model.fit(self.data_states, t=self.time)
            #if getattr(self, 'debug', False):
                #print("\n===== DIAG (orthogonal) =====")
                #self._diagnose_linear_alignment()
        else:
            model = ps.SINDy(
                feature_library=feature_library,
                optimizer=optimizer,
                feature_names=feature_names
            )
            self.model = model
            model.fit(self.data_states, t=self.time, x_dot=self.Xdot)
            #if getattr(self, 'debug', False):
                #print("\n===== DIAG (orthogonal) =====")
                #self._diagnose_linear_alignment()
        eq_list = model.equations()
        print("len(eq_list)=", len(eq_list))
        # Step 1: orthogonal → monomial polynomial (no denormalization)
        equation_list_poly = self._convert_orthogonal_to_polynomial(eq_list)
        # Step 2: denormalize and format, only for Chebyshev and Legendre
        return self._denormalize_and_format(equation_list_poly)
    
    def _recovered_model_orthogonal_OLS(self):
        if self.method not in ('Chebyshev', 'Legendre','LegendreOriginalRange'):
            raise ValueError("_recovered_model_orthogonal_OLS only supports Chebyshev/Legendre.")

        # 1) Build orthogonal features on normalized data
        lib = OrthogonalLibrary(degree=self.poly_degree, method=self.method,include_bias=False)
        # Fit/transform API expects a list of trajectories
        lib.fit([self.data_states.values])
        Phi = lib.transform([self.data_states.values])[0]  # shape (T, n_features)
        feat_names = lib.get_feature_names(input_features=self.features)

        # 2) Derivatives in the *same* space
        t = np.asarray(self.time, dtype=float).reshape(-1)
        if self.Xdot is None:
            X_norm = np.asarray(self.data_states, dtype=float)
            Xdot = np.gradient(X_norm, t, axis=0, edge_order=self.differential_order)
        else:
            # If user supplies Xdot, assume it's already aligned with data_norm order/shape
            Xdot = np.asarray(self.Xdot, dtype=float)
            if Xdot.shape[0] != Phi.shape[0]:
                raise ValueError(f"Xdot length {Xdot.shape[0]} != number of samples {Phi.shape[0]}.")
            if Xdot.shape[1] != len(self.features):
                raise ValueError(f"Xdot has {Xdot.shape[1]} columns but there are {len(self.features)} state variables.")

        # 3) OLS for each state derivative column
        eq_list = []  # list of RHS strings, one per state in self.features order
        Phi_mat = np.asarray(Phi, dtype=float)
        # Solve Phi * beta_j ≈ Xdot[:, j]
        for j, var in enumerate(self.features):
            y = Xdot[:, j]
            # lstsq returns (coef, residuals, rank, s)
            beta, *_ = np.linalg.lstsq(Phi_mat, y, rcond=None)
            # Optional small thresholding just to clean tiny numerical noise
            beta[np.isclose(beta, 0, atol=1e-12)] = 0.0
            # Build RHS string with explicit signed coefficients, no space after sign, no leading '+'
            terms = []
            for c, name in zip(beta, feat_names):
                if not np.isfinite(c) or c == 0:
                    continue
                # Use explicit signed coefficient without a space after the sign to satisfy downstream parser
                terms.append(f"{c:+.6g} {name.replace('*', ' ')}")
            rhs = " ".join(terms).lstrip('+')  # drop only the first leading '+' if present
            if rhs.strip() == "":
                rhs = "0"
            eq_list.append(rhs)

        # 4) Convert to original polynomial basis and return formatted DataFrame
        return self._orthogonal_converter(eq_list)

    @staticmethod
    def preprocess_eq(eq):
        eq = eq.replace('^', '**')
        # Convert "number space letter" or "number space variable" to an explicit multiplication sign
        eq = re.sub(r'(?<=\d)\s+(?=[A-Za-z_])', '*', eq)
        return eq

    def _clean_equation_string(self, eq: str) -> str:
        eq = re.sub(r'\+\s+-', '- ', eq)
        eq = re.sub(r'\s+', ' ', eq).strip()
        return eq
    
    def _pretty_equation_rhs(self, eq: str) -> str:
        """Pretty-print RHS: replace '**' -> '^' and '*' -> space; normalize spaces/signs.
        Examples:
        'x1*x2' -> 'x1 x2'
        'x1**2' -> 'x1^2'
        '-2.124*x1*x2' -> '-2.124 x1 x2'
        """
        if eq is None:
            return eq
        s = str(eq)
        def round_number(m):
            val = float(m.group())
            return f"{val:.3f}"
        s = re.sub(r"[-+]?\d*\.\d+(?:[eE][-+]?\d+)?", round_number, s)
        # First replace the power '**' with '^', 
        # then change the remaining '*' to spaces (implicit multiplication)
        s = s.replace('**', '^')
        s = s.replace('*', ' ')
        # Regular spaces and "+ -" combination
        s = re.sub(r'\s+', ' ', s)
        s = re.sub(r'\+\s+-', '- ', s)
        return s.strip()

    def _filter_equation_terms(self, eq_str: str, var_names: list, thr: float):
        """Filter out monomial terms with |coefficient| <= thr from the RHS string.
        Returns (new_eq_str, n_removed)."""
        if eq_str is None:
            return eq_str, 0
        try:
            syms = sp.symbols(var_names)
            pre = self.preprocess_eq(str(eq_str))
            expr = sp.sympify(pre, evaluate=False)
            poly = sp.Poly(expr, *syms, domain='RR')
            terms = poly.terms()
            kept = []
            for exps, coeff in terms:
                cval = float(coeff)
                if abs(cval) > float(thr):
                    kept.append((exps, coeff))
            n_removed = len(terms) - len(kept)
            if n_removed <= 0:
                return self._clean_equation_string(str(sp.expand(expr))), 0
            new_expr = 0
            for exps, coeff in kept:
                mon = 1
                for s, p in zip(syms, exps):
                    if p != 0:
                        mon *= s**p
                new_expr += coeff * mon
            new_expr = sp.expand(new_expr)
            return self._clean_equation_string(str(new_expr)), n_removed
        except Exception:
            # If parsing fails, return original string without filtering
            return eq_str, 0

    def get_final_coefficients(self, as_dataframe: bool = True):
        """Extract coefficients for every term in the *final* model_expression
        (i.e., after conversion/denormalization/pretty formatting).

        Returns
        -------
        pd.DataFrame or dict
            If as_dataframe=True (default): a tidy DataFrame with columns
            [state, term, coefficient]. Otherwise, returns a dict mapping
            state -> {term -> coefficient}.
        """
        if not hasattr(self, 'model_expression') or self.model_expression is None:
            raise RuntimeError("model_expression is not available yet. Fit the model first.")

        df = self.model_expression
        # be robust to both 'Variable' and historical misspelling 'Varaiable'
        var_col = 'Variable' if 'Variable' in df.columns else ('Varaiable' if 'Varaiable' in df.columns else df.columns[0])
        eq_col = 'Equation' if 'Equation' in df.columns else df.columns[1]

        # prepare symbol table for parsing
        var_syms = {name: sp.symbols(name) for name in self.features}
        syms = tuple(var_syms[v] for v in self.features)
        transf = standard_transformations + (implicit_multiplication_application,)

        rows = []
        out_map = {}

        for _, row in df.iterrows():
            lhs = str(row[var_col]).strip()
            # try to extract the state name from 'dX/dt' pattern; otherwise keep lhs
            m = re.match(r"^d(?P<var>.+)/dt$", lhs)
            state = m.group('var') if m else lhs

            rhs_pretty = str(row[eq_col])
            # prepare for parsing: '^' -> '**'
            rhs = rhs_pretty.replace('^', '**')
            try:
                expr = parse_expr(rhs, local_dict=var_syms, transformations=transf, evaluate=False)
            except Exception:
                # fallback to basic sympify
                expr = sp.sympify(rhs, evaluate=False)

            poly = sp.Poly(expr, *syms, domain='RR')

            term_map = {}
            for exps, coeff in poly.terms():
                # build human-readable term string in our library style
                parts = []
                for v, p in zip(self.features, exps):
                    if p == 0:
                        continue
                    if p == 1:
                        parts.append(v) 
                    else:
                        parts.append(f"{v}^{p}")
                term = ' '.join(parts) if parts else '1'
                term_map[term] = float(coeff)
                rows.append({'state': state, 'term': term, 'coefficient': float(coeff)})

            out_map[state] = term_map

        if as_dataframe:
            # stable sort: by state, then by total degree desc, then lexicographically
            def term_degree(t):
                if t == '1':
                    return 0
                deg = 0
                for tok in t.split():
                    if '^' in tok:
                        deg += int(tok.split('^')[1])
                    else:
                        deg += 1
                return deg
            rows.sort(key=lambda r: (r['state'], -term_degree(r['term']), r['term']))
            return pd.DataFrame(rows, columns=['state', 'term', 'coefficient'])
        else:
            return out_map

    def _orthogonal_converter(self, eq_list):
        converter = OrthogonalToPolynomialConverter(max_degree=self.poly_degree, basis=self.method)
        polynomial_model = converter.convert_sindy_model(eq_list, self.features)

        denormalizer = MatrixEquationDenormalizer(self.L, self.U, self.method)
        # Build equation_list in the exact self.features order
        equation_list = []
        for var in self.features:
            poly = polynomial_model.get(var)
            if poly is None:
                continue
            equation_list.append(f"d{var}/dt = {poly._to_string()}")

        #original_equations = equation_list
        original_equations = denormalizer.denormalize_equations(equation_list)

        # Parse original_equations of the form "dx/dt = ..." into {var: rhs}
        eq_map = {}
        for eq in original_equations:
            parts = eq.split('=', 1)
            lhs = parts[0].strip()
            rhs = parts[1].strip() if len(parts) > 1 else ''
            m = re.match(r"^d(?P<var>.+)/dt$", lhs)
            if m:
                var_name = m.group('var').strip()
                eq_map[var_name] = rhs

        # Build rows strictly following self.features; fall back by index if needed
        states, rhs_raw = [], []
        for i, var in enumerate(self.features):
            if var in eq_map:
                rhs_raw.append(eq_map[var])
                states.append(f'd{var}/dt')
            else:
                # Fallback: use i-th equation if available
                if i < len(original_equations):
                    parts = original_equations[i].split('=', 1)
                    rhs_fallback = parts[1].strip() if len(parts) > 1 else original_equations[i].strip()
                    rhs_raw.append(rhs_fallback)
                else:
                    rhs_raw.append('')
                states.append(f'd{var}/dt')

        def clean(eq: str) -> str:
            eq = re.sub(r'\+\s+-', '- ', eq)
            eq = re.sub(r'\s+', ' ', eq).strip()
            return eq
        rhs = [clean(s) for s in rhs_raw]

        # Optional post-expansion hard threshold on final polynomial equations
        if getattr(self, 'after_threshold', None) is not None and float(self.after_threshold) > 0:
            thr = float(self.after_threshold)
            rhs_filtered = []
            for i, eq in enumerate(rhs):
                new_eq, n_removed = self._filter_equation_terms(eq, self.features, thr)
                rhs_filtered.append(new_eq)
                if n_removed > 0:
                    print(f"[AFTER-THRESH] filtered {n_removed} term(s) in d{self.features[i]}/dt with threshold={thr}")
            rhs = rhs_filtered
        
        rhs = [self._pretty_equation_rhs(s) for s in rhs]

        df = pd.DataFrame({
            'Variable': states,
            'Equation': rhs
        })
        return df

    def _expand_brackets(self,equation):
        equation = equation.replace(' ','')
        equation = self._protect_function_parentheses(equation)
        # Expand brackets in the equation like 0.5*(x1+x2) -> 0.5*x1+0.5*x2
        while '(' in equation:
            start = -1
            for i,char in enumerate(equation):
                if char == '(':
                    start = i
                elif char == ')' and start != -1:
                    bracket_content = equation[start+1:i]

                    coeff_start = self._find_coefficient_start(equation, start)
                    coefficient_part = equation[coeff_start:start]
                    expanded = self._expand_single_bracket(coefficient_part,bracket_content)
                    equation = equation[:coeff_start] + expanded + equation[i+1:]
                    break
        equation = self._restore_function_parentheses(equation)

        return equation
    
    def _protect_function_parentheses(self,equation):
        function_pattern = r'([a-zA-Z_][a-zA-Z0-9_]*)\(([^()]*)\)'
        self.function_substitutions = {}
        counter = 0
        while re.search(function_pattern, equation):
            match = re.search(function_pattern, equation)
            if match:
                full_func = match.group(0)
                placeholder = f'__FUNC_{counter}__'
                self.function_substitutions[placeholder] = full_func
                equation = equation.replace(full_func, placeholder, 1)
                counter += 1

        return equation
    
    def _restore_function_parentheses(self, equation):
        if hasattr(self, 'function_substitutions'):
            for placeholder, original in self.function_substitutions.items():
                equation = equation.replace(placeholder, original)

        return equation

    def _find_coefficient_start(self, equation, bracket_start):
            """Coefficient starting position search"""
            i = bracket_start - 1
            
            # Search forward until an operator or the beginning of a string is encountered
            while i >= 0:
                char = equation[i]
                if char in '+-' and i != bracket_start - 1:
                    # If it is a symbol and not immediately adjacent to a bracket, stop
                    if i == 0 or equation[i-1] in '+-*/':
                        # This is a single symbol
                        break
                    else:
                        # This could be part of the expression
                        i -= 1
                elif char in '*/':
                    i -= 1
                elif char.isalnum() or char in '._':
                    i -= 1
                else:
                    break
            
            return i + 1 if i >= 0 else 0
    
    def _expand_single_bracket(self, coefficient, bracket_content):
        """Single bracket expansion"""
        # Split bracket contents
        bracket_terms = self._split_equation_terms(bracket_content)
        
        # Treatment coefficient
        coeff = coefficient.strip()
        if coeff.endswith('*'):
            coeff = coeff[:-1]
        
        # Processing Symbols
        coeff_sign = 1
        coeff_value = coeff
        
        if coeff.startswith('-'):
            coeff_sign = -1
            coeff_value = coeff[1:] if len(coeff) > 1 else ""
        elif coeff.startswith('+'):
            coeff_value = coeff[1:] if len(coeff) > 1 else ""
        
        # Expand each item
        expanded_terms = []
        for term in bracket_terms:
            term = term.strip()
            term_sign = 1
            
            if term.startswith('+'):
                term = term[1:]
            elif term.startswith('-'):
                term_sign = -1
                term = term[1:]
            
            final_sign = coeff_sign * term_sign
            
            # Build expansion items
            if coeff_value:
                if final_sign == -1:
                    expanded_term = '-' + coeff_value + '*' + term
                else:
                    expanded_term = coeff_value + '*' + term
            else:
                if final_sign == -1:
                    expanded_term = '-' + term
                else:
                    expanded_term = term
            
            expanded_terms.append(expanded_term)
        
        # Connection Item
        result = ''
        for i, term in enumerate(expanded_terms):
            if i == 0:
                result = term
            else:
                if term.startswith('-'):
                    result += term
                else:
                    result += '+' + term
        
        return result
    
    def _split_equation_terms(self,equation:str):
        # Split equation into without preserving signs.
        terms = []
        current_term = ""

        i = 0
        while i < len(equation):
            char = equation[i]
            if char == '+' or char == '-':
                if current_term:
                    terms.append(current_term)
                if char == '-':
                    current_term = '-'
                else:
                    current_term = ''
            else:
                current_term += char
            i += 1
        
        if current_term:
            terms.append(current_term)

        return terms

    def _plot_pareto(self):
        """Compute Pareto-like curves of error vs threshold.
        This version fits a fresh model for each threshold and computes scores immediately,
        avoiding the fragile pattern of reusing a single optimizer/model afterward.
        """
        from sklearn.metrics import mean_squared_error as _mse

        # Train/test split on index (no shuffle to preserve time ordering)
        indices = np.arange(len(self.data_states))
        train_indices, test_indices = train_test_split(
            indices, test_size=0.33, random_state=27, shuffle=False
        )

        # Prepare data by basis type
        method = self.method
        feature_names = self.features
        t = self.time
        t_train = t[train_indices]
        t_test = t[test_indices]

        # Prepare X / Xdot on the appropriate space
        if method == 'Monomial':
            X_all = np.asarray(self.data_states, dtype=np.float64)
            if self.Xdot is None:
                Xdot_all = np.gradient(X_all, t, axis=0, edge_order=self.differential_order)
            else:
                Xdot_all = np.asarray(self.Xdot, dtype=np.float64)
            X_train, X_test = X_all[train_indices], X_all[test_indices]
            Xdot_train, Xdot_test = Xdot_all[train_indices], Xdot_all[test_indices]
            feature_library = ps.PolynomialLibrary(self.poly_degree, include_bias=False)
        elif method in ('Chebyshev', 'Legendre'):
            # Use normalized data for orthogonal libraries
            X_all = np.asarray(self.data_norm, dtype=np.float64)
            # For fair scoring, compute derivative in the same normalized space
            Xdot_all = np.gradient(X_all, t, axis=0, edge_order=self.differential_order)
            X_train, X_test = X_all[train_indices], X_all[test_indices]
            Xdot_train, Xdot_test = Xdot_all[train_indices], Xdot_all[test_indices]
            feature_library = OrthogonalLibrary(degree=self.poly_degree, method=method)
        else:
            raise ValueError(f"Unknown method: {method}")

        thresholds = self.threshold_scan if self.threshold_scan is not None else [self.threshold]
        mse_deriv = np.zeros(len(thresholds))
        mse_traj = np.zeros(len(thresholds))

        for k, thr in enumerate(thresholds):
            optimizer = ps.STLSQ(threshold=thr)
            model = ps.SINDy(
                feature_library=feature_library,
                optimizer=optimizer,
                feature_names=feature_names,
            )
            # Fit on training set
            model.fit(X_train, t=t_train, x_dot=Xdot_train)

            # 1) Derivative-domain error on test set
            try:
                mse_deriv[k] = model.score(X_test, t=t_test, x_dot=Xdot_test, metric=_mse)
            except Exception:
                # If score fails (shape mismatch, etc.), fall back to manual MSE
                Xdot_pred = model.predict(X_test)
                mse_deriv[k] = np.mean((Xdot_test - Xdot_pred) ** 2)

            # 2) Trajectory-domain error on test set via simulate
            try:
                x0 = X_test[0]
                X_sim = model.simulate(x0, t_test, integrator="odeint")
                # If simulate explodes, clip to avoid NaNs in MSE
                if np.any(~np.isfinite(X_sim)) or np.any(np.abs(X_sim) > 1e6):
                    X_sim = np.clip(X_sim, -1e6, 1e6)
                mse_traj[k] = np.mean((X_test - X_sim) ** 2)
            except Exception:
                mse_traj[k] = np.nan

        # Plot (do not rely on external helper)
        plt.figure()
        plt.semilogy(thresholds, mse_deriv, "o-", label=r"$\dot{X}$ RMSE")
        plt.xlabel(r"$\lambda$")
        plt.xticks(thresholds, [f"{v:.1e}" for v in thresholds])
        plt.ylabel(r"Error")
        plt.title("Derivative-domain error vs threshold")
        plt.grid(True, alpha=0.3)
        plt.tight_layout()

        plt.figure()
        plt.semilogy(thresholds, mse_traj, "o-", label="Trajectory RMSE")
        plt.xlabel(r"$\lambda$")
        plt.ylabel("Error")
        plt.xticks(thresholds, [f"{v:.1e}" for v in thresholds])
        plt.title("Trajectory-domain error vs threshold")
        plt.grid(True, alpha=0.3)
        plt.tight_layout()

        return thresholds, mse_deriv, mse_traj
    

def plot_pareto(coefs, opt, model, threshold_scan, x_test, t_test):
        #formatter = LogFormatterExponent(base=10)
        mse = np.zeros(len(threshold_scan))
        mse_sim = np.zeros(len(threshold_scan))
        for i in range(len(threshold_scan)):
            opt.coef_ = coefs[i]
            mse[i] = model.score(x_test, t=t_test, metric=mean_squared_error)
            x_test_sim = model.simulate(x_test.iloc[0].to_numpy(), t_test, integrator="odeint")
            if np.any(x_test_sim > 1e4):
                x_test_sim = 1e4
            # Ensure subtraction is performed on compatible NumPy arrays and result is a scalar
            mse_sim[i] = np.mean((x_test.values - x_test_sim) ** 2)
        plt.figure()
        plt.semilogy(threshold_scan, mse, "bo")
        plt.semilogy(threshold_scan, mse, "b")
        plt.ylabel(r"$\dot{X}$ RMSE", fontsize=20)
        plt.xlabel(r"$\lambda$", fontsize=20)
        plt.xticks(fontsize=14, rotation=45) 
        plt.tight_layout() 
        plt.yticks(fontsize=16)
        plt.grid(True)
        #plt.gca().xaxis.set_major_formatter(formatter)
        plt.figure()

        plt.semilogy(threshold_scan, mse_sim, "bo")
        plt.semilogy(threshold_scan, mse_sim, "b")
        plt.ylabel(r"$\dot{X}$ RMSE", fontsize=20)
        plt.xlabel(r"$\lambda$", fontsize=20)
        plt.xticks(ontsize=14, rotation=45) 
        plt.tight_layout() 
        plt.yticks(fontsize=16)
        plt.grid(True)
        #plt.gca().xaxis.set_major_formatter(formatter)



class MonomialToLegendreConverter:
    """
    Converts SINDy-recovered ODEs from monomial basis to Legendre polynomial basis
    using the library definitions from Basis.py.
    
    Why generate libraries?
    -----------------------
    Even though SINDy already used libraries, we need to regenerate them here to:
    1. Parse the monomial terms in SINDy's output equation
    2. Build the mathematical mapping (conversion matrix) between bases
    3. Solve the inverse problem: given monomial coefficients, find Legendre coefficients
    
    The libraries here should match your SINDy configuration exactly to ensure
    consistency in the conversion.
    """
    
    def __init__(self, data, max_degree=3, normalize=False, include_bias=False):
        """
        Initialize the converter using your library definitions.
        
        Parameters:
        -----------
        data : pd.DataFrame
            The original data used for SINDy (with time column)
        max_degree : int
            Maximum polynomial degree to consider
        normalize : bool
            Whether to normalize the data to [-1, 1] range (recommended for Legendre)
        include_bias : bool
            Whether to include constant term (should match your SINDy setup)
            Default False to match your configuration
        """
        self.data = data
        self.max_degree = max_degree
        self.normalize = normalize
        self.include_bias = include_bias  # Should match your SINDy setup
        
        # Standardize column names and identify state variables
        self.data_std, self.time_col = standardize_columns(data)
        self.data_states = self.data_std.drop(columns=self.time_col)
        self.n_states = len(self.data_states.columns)
        
        # Create symbolic variables matching standardized names
        self.state_symbols = symbols([col for col in self.data_states.columns])
        if self.n_states == 1:
            self.state_symbols = (self.state_symbols,)
        
        # Handle normalization if requested
        if normalize:
            self.data_norm, self.L, self.U = normalization(self.data_states)
        else:
            self.data_norm = self.data_states
            self.L = {col: -1 for col in self.data_states.columns}
            self.U = {col: 1 for col in self.data_states.columns}
        
        # Generate basis libraries using your classes
        self._generate_libraries()
        
    def _generate_libraries(self):
        """Generate monomial and Legendre libraries using your library classes.
        This should match your SINDy configuration exactly."""
        
        # Generate monomial library
        self.monomial_lib_data = {}
        self.monomial_lib_names = []
        
        # Add constant term only if include_bias is True
        if self.include_bias:
            self.monomial_lib_names.append('1')
            self.monomial_lib_data['1'] = np.ones(len(self.data_states))
        
        # Collect all terms up to max_degree
        for degree in range(1, self.max_degree + 1):
            mono_obj = Monomials(self.data, degree)
            lib_df = mono_obj._generate_library()
            
            # Store the transformed data
            for col in lib_df.columns:
                if col not in self.monomial_lib_data:
                    self.monomial_lib_data[col] = lib_df[col].values
                    self.monomial_lib_names.append(col)
        
        # Generate Legendre library using OrthogonalLibrary
        # This should match your SINDy configuration
        self.legendre_obj = OrthogonalLibrary(
            degree=self.max_degree,
            method='Legendre',
            include_interaction=True,
            interaction_only=False,
            include_bias=self.include_bias  # Match your SINDy setup
        )
        
        # Fit the library to get the structure
        self.legendre_obj.fit([self.data_norm.values])
        
        # Get feature names for Legendre basis
        self.legendre_lib_names = self.legendre_obj.get_feature_names(
            input_features=list(self.data_states.columns)
        )
        
        # Transform data to get Legendre features
        legendre_transformed = self.legendre_obj.transform([self.data_norm.values])[0]
        self.legendre_lib_data = {}
        for i, name in enumerate(self.legendre_lib_names):
            self.legendre_lib_data[name] = legendre_transformed[:, i]
    
    def _parse_equation_to_coeffs(self, equation_str):
        """
        Parse equation string to extract monomial coefficients.
        Adapted from Terms_Identification_recovered for better handling of SINDy output.
        
        Parameters:
        -----------
        equation_str : str
            RHS of the equation as a string (e.g., "-34344.017*x1**2 + 6066.330*x1*x3 + ...")
            
        Returns:
        --------
        np.ndarray : Coefficient vector aligned with monomial library
        """
        # Initialize coefficient vector
        coeffs = np.zeros(len(self.monomial_lib_names))
        
        # Clean the equation: keep spaces because library terms may be space-separated (e.g., 'x1 x2')
        equation_str = str(equation_str).strip()
        
        # Split into terms while preserving signs
        terms = self._split_equation_into_terms(equation_str)
        
        for term in terms:
            # Extract coefficient and variable part from each term
            coeff, var_part = self._extract_coefficient_and_variables(term)
            
            if var_part == '':
                # Constant term
                if self.include_bias and '1' in self.monomial_lib_names:
                    idx = self.monomial_lib_names.index('1')
                    coeffs[idx] += coeff
                elif not self.include_bias and abs(coeff) > 1e-10:
                    print(f"Warning: Found constant term {coeff} but include_bias=False")
            else:
                # Convert to library format
                lib_format = self._convert_to_library_format(var_part)
                
                # Find in library
                if lib_format in self.monomial_lib_names:
                    idx = self.monomial_lib_names.index(lib_format)
                    coeffs[idx] += coeff
                else:
                    # Debug: print what couldn't be found
                    print(f"Warning: Term '{lib_format}' not found in library")
                    print(f"  Available similar terms: {[t for t in self.monomial_lib_names if any(v in t for v in lib_format.split())][:5]}")
        
        return coeffs
    
    def _split_equation_into_terms(self, equation):
        """Split equation into terms, handling + and - correctly."""
        terms = []
        current_term = ""
        
        i = 0
        while i < len(equation):
            char = equation[i]
            
            if char in ['+', '-'] and i > 0:
                # Check if this is actually a sign for the next term
                # (not part of scientific notation like 1e-3)
                if i > 0 and equation[i-1] not in ['e', 'E']:
                    if current_term:
                        terms.append(current_term)
                    current_term = char if char == '-' else ''
                else:
                    current_term += char
            else:
                current_term += char
            i += 1
        
        if current_term and current_term not in ['+', '-', '']:
            terms.append(current_term)
        
        return terms
    
    def _extract_coefficient_and_variables(self, term):
        """
        Extract numerical coefficient and variable part from a term.
        Examples: 
            '-34.5*x1**2' -> (-34.5, 'x1**2')
            'x1*x2' -> (1.0, 'x1*x2')
            '-x1' -> (-1.0, 'x1')
            '5.0' -> (5.0, '')
        """
        term = str(term).strip()
        if not term:
            return 0.0, ''

        # Handle leading sign
        sign = 1.0
        if term[0] == '-':
            sign = -1.0
            term = term[1:]
        elif term[0] == '+':
            term = term[1:]
        term = term.strip()
        if not term:
            return 0.0, ''

        # Pattern: optional numeric coeff followed by optional "*vars"
        # Supports scientific notation like 1e-3
        m = re.match(r'^(\d*\.?\d+(?:[eE][+-]?\d+)?)\*?(.*)$', term)
        if m:
            coeff_str = m.group(1)
            rest = m.group(2)
            if coeff_str:
                try:
                    coeff = float(coeff_str)
                except ValueError:
                    coeff = 1.0
            else:
                coeff = 1.0
            var_part = rest.strip()
            return sign * coeff, var_part

        # No leading number -> implicit coefficient 1, entire term is variables
        return sign * 1.0, term

    def _convert_to_library_format(self, var_part):
        """
        Convert a variable product string to the monomial library naming.
        Input examples: 'x1 x2', 'x1*x2', 'x1**2*x3', 'x1^2 x3', 'x1x2'
        Output examples: 'x1 x2', 'x1 x2', 'x1^2 x3', 'x1^2 x3', 'x1 x2'
        """
        var_part = str(var_part).strip()
        if var_part == '' or var_part == '1':
            return '1' if self.include_bias else ''

        # Helper to accumulate tokens into power_map
        def accumulate_tokens(tokens):
            pmap = {}
            for tok in tokens:
                if not tok:
                    continue
                m = re.match(r'^(x\d+)(?:\*\*(\d+)|\^(\d+))?$', tok)
                if m:
                    var = m.group(1)
                    p = m.group(2) or m.group(3)
                else:
                    # Try a looser match like xA, xalpha, etc.
                    m2 = re.match(r'^(x\w+)(?:\*\*(\d+)|\^(\d+))?$', tok)
                    if not m2:
                        continue
                    var = m2.group(1)
                    p = m2.group(2) or m2.group(3)
                exp = int(p) if p else 1
                pmap[var] = pmap.get(var, 0) + exp
            return pmap

        # First try splitting by '*' and whitespace simultaneously
        raw = var_part.replace(' ', ' ').strip()
        tokens = re.split(r'[\*\s]+', raw)
        power_map = accumulate_tokens(tokens)

        # If nothing parsed and there are no separators, support implicit multiplication like 'x1x2x3'
        if not power_map:
            implicit_tokens = []
            for m in re.finditer(r'(x\d+)(?:\*\*(\d+)|\^(\d+))?', var_part):
                var = m.group(1)
                p = m.group(2) or m.group(3)
                implicit_tokens.append(var if not p else f"{var}^{p}")
            if implicit_tokens:
                power_map = accumulate_tokens(implicit_tokens)

        if not power_map:
            return ''

        # Build normalized library name: sort variables, use ^ only if power > 1
        parts = []
        for var in sorted(power_map.keys(), key=lambda s: (len(s), s)):
            exp = power_map[var]
            if exp == 1:
                parts.append(var)
            else:
                parts.append(f"{var}^{exp}")
        return ' '.join(parts)
    
    def _build_conversion_matrix(self):
        """
        Build the conversion matrix from Legendre to monomial basis.
        Maps Legendre coefficients to monomial coefficients.
        
        Returns:
        --------
        numpy.ndarray : Conversion matrix M where M @ alpha_legendre = alpha_monomial
        """
        n_mono = len(self.monomial_lib_names)
        n_leg = len(self.legendre_lib_names)
        
        # Create conversion matrix
        M = np.zeros((n_mono, n_leg))
        
        # For each Legendre basis function, express it in monomial basis
        for j, leg_name in enumerate(self.legendre_lib_names):
            # Get Legendre basis function values
            leg_values = self.legendre_lib_data[leg_name]
            
            # Fit monomials to approximate this Legendre function
            # Using least squares: find coeffs such that Σ coeffs_i * mono_i ≈ leg_j
            mono_matrix = np.column_stack([self.monomial_lib_data[name] 
                                          for name in self.monomial_lib_names])
            
            # Solve for coefficients
            coeffs, _, _, _ = lstsq(mono_matrix, leg_values)
            
            # Store in conversion matrix
            M[:, j] = coeffs
        
        return M
    
    def convert_equation(self, equation_str):
        """
        Convert a single equation from monomial to Legendre basis.
        
        Parameters:
        -----------
        equation_str : str
            RHS of the equation in monomial form
            
        Returns:
        --------
        tuple : (legendre_coeffs, legendre_expression_str)
        """
        # Parse monomial equation to get coefficient vector
        alpha_mono = self._parse_equation_to_coeffs(equation_str)
        
        # Build conversion matrix
        M = self._build_conversion_matrix()
        
        # Solve for Legendre coefficients: M @ alpha_leg = alpha_mono
        alpha_leg, _, _, _ = lstsq(M, alpha_mono)
        
        # Threshold small coefficients
        alpha_leg[np.abs(alpha_leg) < 1e-10] = 0
        
        # Build Legendre expression string
        terms = []
        for i, (coeff, name) in enumerate(zip(alpha_leg, self.legendre_lib_names)):
            if abs(coeff) > 1e-10:
                if name == '1':
                    terms.append(f"{coeff:.6f}")
                else:
                    if coeff > 0 and len(terms) > 0:
                        terms.append(f"+ {coeff:.6f}*{name}")
                    else:
                        terms.append(f"{coeff:.6f}*{name}")
        
        legendre_expr = " ".join(terms) if terms else "0"
        
        return alpha_leg, legendre_expr
    
    def convert_dataframe(self, df, state_col=None, equation_col=None):
        """
        Convert a dataframe of SINDy results from monomial to Legendre basis.
        
        Parameters:
        -----------
        df : pd.DataFrame
            DataFrame with SINDy results
        state_col : str, optional
            Name of the column containing state variables (e.g., 'Variable', 'state')
            If None, will try to auto-detect
        equation_col : str, optional
            Name of the column containing equations (e.g., 'Equation', 'equation')
            If None, will try to auto-detect
            
        Returns:
        --------
        pd.DataFrame : DataFrame with columns ['state', 'monomial_eq', 'legendre_eq', 
                                               'legendre_coeffs', 'validation_error']
        """
        # Auto-detect column names if not provided
        if state_col is None:
            possible_state_cols = ['Variable', 'variable', 'State', 'state', 'Feature', 'feature']
            for col in possible_state_cols:
                if col in df.columns:
                    state_col = col
                    break
            if state_col is None:
                state_col = df.columns[0]  # Default to first column
                
        if equation_col is None:
            possible_eq_cols = ['Equation', 'equation', 'RHS', 'rhs', 'Expression', 'expression']
            for col in possible_eq_cols:
                if col in df.columns:
                    equation_col = col
                    break
            if equation_col is None:
                equation_col = df.columns[1]  # Default to second column
        
        results = []
        
        for idx, row in df.iterrows():
            state = row[state_col]
            monomial_eq = row[equation_col]
            
            print(f"Converting {state}...")
            
            # Convert to Legendre basis
            legendre_coeffs, legendre_expr = self.convert_equation(str(monomial_eq))
            
            # Validate conversion
            error = self.validate_conversion(str(monomial_eq), legendre_coeffs)
            
            results.append({
                'state': state,
                'monomial_eq': monomial_eq,
                'legendre_eq': legendre_expr,
                'legendre_coeffs': legendre_coeffs,
                'validation_error': error
            })
            
            print(f"  Validation error: {error:.2e}")
        
        return pd.DataFrame(results)
    
    def validate_conversion(self, monomial_eq, legendre_coeffs, n_test_points=100):
        """
        Validate conversion by comparing evaluations at test points.
        
        Parameters:
        -----------
        monomial_eq : str
            Original equation in monomial form
        legendre_coeffs : array
            Coefficients for Legendre basis
        n_test_points : int
            Number of random test points
            
        Returns:
        --------
        float : Maximum absolute error
        """
        # Generate random test points
        if self.normalize:
            # Test points in [-1, 1]
            test_points = np.random.uniform(-1, 1, (n_test_points, self.n_states))
        else:
            # Test points in original range
            test_points = np.zeros((n_test_points, self.n_states))
            for i, col in enumerate(self.data_states.columns):
                test_points[:, i] = np.random.uniform(self.L[col], self.U[col], n_test_points)
        
        # Evaluate monomial expression
        mono_coeffs = self._parse_equation_to_coeffs(monomial_eq)
        
        max_error = 0
        for point in test_points:
            # Create test dataframe with single point
            test_df = pd.DataFrame([point], columns=self.data_states.columns)
            
            # Evaluate monomial expression
            mono_val = 0
            for coeff, name in zip(mono_coeffs, self.monomial_lib_names):
                if abs(coeff) > 1e-10:
                    if name == '1':
                        mono_val += coeff
                    else:
                        # Evaluate monomial term at test point
                        term_val = 1
                        # Parse the monomial term
                        parts = name.replace('^', '**').split(' ')
                        for part in parts:
                            if '**' in part:
                                var, power = part.split('**')
                                var_idx = list(self.data_states.columns).index(var)
                                term_val *= point[var_idx] ** int(power)
                            else:
                                var_idx = list(self.data_states.columns).index(part)
                                term_val *= point[var_idx]
                        mono_val += coeff * term_val
            
            # Evaluate Legendre expression
            if self.normalize:
                # Normalize test point
                norm_point = np.zeros(self.n_states)
                for i, col in enumerate(self.data_states.columns):
                    norm_point[i] = 2 * (point[i] - self.L[col]) / (self.U[col] - self.L[col]) - 1
            else:
                norm_point = point
            
            # Transform point using Legendre library
            leg_features = self.legendre_obj.transform([norm_point.reshape(1, -1)])[0]
            leg_val = np.dot(legendre_coeffs, leg_features[0])
            
            error = abs(mono_val - leg_val)
            max_error = max(max_error, error)
        
        return max_error
    
    def verify_sindy_compatibility(self, sindy_library_config):
        """
        Verify that the converter configuration matches your SINDy library setup.
        
        Parameters:
        -----------
        sindy_library_config : dict
            Dictionary with SINDy configuration:
            {'method': 'Legendre', 'degree': 2, 'include_bias': False, ...}
            
        Returns:
        --------
        bool : True if configurations match
        list : List of any mismatches found
        """
        mismatches = []
        
        if 'degree' in sindy_library_config:
            if sindy_library_config['degree'] != self.max_degree:
                mismatches.append(f"Degree mismatch: SINDy={sindy_library_config['degree']}, Converter={self.max_degree}")
        
        if 'include_bias' in sindy_library_config:
            if sindy_library_config['include_bias'] != self.include_bias:
                mismatches.append(f"Bias mismatch: SINDy={sindy_library_config['include_bias']}, Converter={self.include_bias}")
        
        if 'method' in sindy_library_config:
            if sindy_library_config['method'] != 'Legendre':
                mismatches.append(f"Method mismatch: SINDy={sindy_library_config['method']}, Converter=Legendre")
        
        if mismatches:
            print("Configuration mismatches found:")
            for mismatch in mismatches:
                print(f"  - {mismatch}")
            return False, mismatches
        else:
            print("Configuration matches SINDy setup ✓")
            return True, []